//! Code generation: lower the erased eidos computational core to `no_std` Rust.
//!
//! The output is a complete, self-contained `#![no_std]` crate that depends on
//! nothing but `core`. All proof machinery (refinements, contracts, the kernel,
//! the QF_LRA verifier) has been erased, so no verification artifact leaks into
//! the generated source and there is zero runtime cost from verification.
//!
//! Array helpers (`eidos_map`, `eidos_zip`, `eidos_magnitude`, `eidos_len`) are
//! emitted as `const`-generic, stack-only functions, so generated code never
//! allocates.

use eidos_erasure::{CExpr, CExprKind, CoreFun, CoreModule, CoreType, StructDef};

/// Lower an erased core module to a `no_std` Rust source string.
pub fn codegen(module: &CoreModule) -> String {
    let mut out = String::new();
    out.push_str("#![no_std]\n");
    out.push_str("// Generated by tpt-eidos (erasure + codegen). Do not edit by hand.\n");
    out.push_str("// This module was verified by the eidos kernel; all proof terms\n");
    out.push_str("// have been erased. It depends only on `core`.\n\n");

    out.push_str(&prelude());
    out.push('\n');

    for s in &module.structs {
        out.push_str(&gen_struct(s));
        out.push('\n');
    }
    if !module.structs.is_empty() {
        out.push('\n');
    }

    for f in &module.fns {
        out.push_str(&gen_fun(f));
        out.push('\n');
    }

    out
}

fn prelude() -> String {
    "\
#[inline]
pub fn eidos_len<const N: usize>(_a: [f64; N]) -> usize {
    N
}

#[inline]
pub fn eidos_sqrt(x: f64) -> f64 {
    if x <= 0.0 {
        return 0.0;
    }
    let mut g = x;
    let mut i = 0usize;
    while i < 32 {
        g = 0.5 * (g + x / g);
        i += 1;
    }
    g
}

#[inline]
pub fn eidos_magnitude<const N: usize>(a: [f64; N]) -> f64 {
    let mut s = 0.0f64;
    let mut i = 0usize;
    while i < N {
        s = s + a[i] * a[i];
        i += 1;
    }
    eidos_sqrt(s)
}

#[inline]
pub fn eidos_map<const N: usize, T, R, F>(a: [T; N], f: F) -> [R; N]
where
    T: Copy,
    F: Fn(T) -> R,
{
    core::array::from_fn(|i| f(a[i]))
}

#[inline]
pub fn eidos_zip<const N: usize>(a: [f64; N], b: [f64; N]) -> [(f64, f64); N] {
    core::array::from_fn(|i| (a[i], b[i]))
}
"
    .to_string()
}

fn gen_struct(s: &StructDef) -> String {
    let fields = s
        .fields
        .iter()
        .map(|(n, t)| format!("    pub {}: {},", n, gen_type(t)))
        .collect::<Vec<_>>()
        .join("\n");
    format!("pub struct {} {{\n{}\n}}\n", s.name, fields)
}

fn gen_fun(f: &CoreFun) -> String {
    let params = f
        .params
        .iter()
        .map(|(n, t)| format!("{}: {}", n, gen_type(t)))
        .collect::<Vec<_>>()
        .join(", ");
    let ret = gen_type(&f.ret);
    let body = gen_block(&f.body, 1);
    format!("pub fn {} ({}) -> {} {{\n{}}}\n", f.name, params, ret, body)
}

fn gen_type(t: &CoreType) -> String {
    match t {
        CoreType::Base(s) => base_type(s),
        CoreType::Array(inner, n) => format!("[{}; {}]", gen_type(inner), n),
        CoreType::Named(n) => n.clone(),
    }
}

fn base_type(s: &str) -> String {
    match s {
        "Unit" => "()".to_string(),
        other => other.to_string(),
    }
}

/// Render an expression in *value* position (no trailing semicolon).
fn gen_expr(e: &CExpr) -> String {
    match &e.kind {
        CExprKind::Num(n) => float_lit(*n),
        CExprKind::Bool(b) => b.to_string(),
        CExprKind::Var(v) => v.clone(),
        CExprKind::ArrayLit(es) => {
            let elems = es.iter().map(gen_expr).collect::<Vec<_>>().join(", ");
            format!("[{}]", elems)
        }
        CExprKind::Bin { op, a, b } => {
            format!("({} {} {})", gen_expr(a), binop_str(*op), gen_expr(b))
        }
        CExprKind::Un { op, a } => match op {
            eidos_parser::UnOp::Neg => format!("(-{})", gen_expr(a)),
            eidos_parser::UnOp::Not => format!("(!{})", gen_expr(a)),
        },
        CExprKind::If { cond, then, els } => format!(
            "if {} {{ {} }} else {{ {} }}",
            gen_expr(cond),
            gen_block(then, 0),
            gen_block(els, 0)
        ),
        CExprKind::Let { name, value, body } => format!(
            "{{ let {} = {}; {} }}",
            name,
            gen_expr(value),
            gen_block(body, 0)
        ),
        CExprKind::Call { func, args } => {
            let a = args.iter().map(gen_expr).collect::<Vec<_>>().join(", ");
            format!("{}({})", func, a)
        }
        CExprKind::Method { recv, name, args } => gen_method(recv, name, args),
        CExprKind::Lambda { params, body } => {
            format!("|{}| {}", params.join(", "), gen_expr(body))
        }
        CExprKind::Record(fields) => gen_record(e, fields),
        CExprKind::Return(inner) => format!("return {}", gen_expr(inner)),
    }
}

/// Render an expression in *statement / tail* position, adding a semicolon to
/// `return` so it terminates the enclosing block.
fn gen_block(e: &CExpr, _indent: usize) -> String {
    match &e.kind {
        CExprKind::Return(inner) => format!("return {};", gen_expr(inner)),
        CExprKind::If { cond, then, els } => format!(
            "if {} {{\n{}    }} else {{\n{}    }}",
            gen_expr(cond),
            indent_block(&gen_block(then, 0)),
            indent_block(&gen_block(els, 0))
        ),
        CExprKind::Let { name, value, body } => {
            format!(
                "let {} = {};\n{}",
                name,
                gen_expr(value),
                gen_block(body, 0)
            )
        }
        other => {
            let _ = other;
            gen_expr(e)
        }
    }
}

/// Indent every line of `s` by four spaces and ensure it ends with a newline.
fn indent_block(s: &str) -> String {
    let mut out = String::new();
    for line in s.lines() {
        if line.is_empty() {
            out.push('\n');
        } else {
            out.push_str("    ");
            out.push_str(line);
            out.push('\n');
        }
    }
    out
}

fn gen_method(recv: &CExpr, name: &str, args: &[CExpr]) -> String {
    let r = gen_expr(recv);
    match name {
        "magnitude" => format!("eidos_magnitude({})", r),
        "len" => format!("eidos_len({})", r),
        "map" => {
            let lam = args.first().expect("map requires a closure argument");
            let (params, body) = match &lam.kind {
                CExprKind::Lambda { params, body } => (params.clone(), gen_expr(body)),
                _ => (Vec::new(), gen_expr(lam)),
            };
            let recv_is_zip = match &recv.kind {
                CExprKind::Method { name, .. } => name == "zip",
                _ => false,
            };
            let param_str = if recv_is_zip {
                format!("({})", params.join(", "))
            } else {
                params.join(", ")
            };
            format!("eidos_map({}, |{}| {})", r, param_str, body)
        }
        "zip" => {
            let a = args.first().map(gen_expr).unwrap_or_default();
            format!("eidos_zip({}, {})", r, a)
        }
        _ => {
            if args.is_empty() {
                format!("{}.{}", r, name)
            } else {
                let a = args.iter().map(gen_expr).collect::<Vec<_>>().join(", ");
                format!("{}.{}({})", r, name, a)
            }
        }
    }
}

fn gen_record(e: &CExpr, fields: &[(String, CExpr)]) -> String {
    let name = match &e.ty {
        CoreType::Named(n) => Some(n.clone()),
        _ => None,
    };
    let body = fields
        .iter()
        .map(|(n, v)| format!("{}: {}", n, gen_expr(v)))
        .collect::<Vec<_>>()
        .join(", ");
    match name {
        Some(n) => format!("{} {{ {} }}", n, body),
        None => format!("({})", body),
    }
}

fn float_lit(n: f64) -> String {
    let s = format!("{n}");
    if s.contains('.') || s.contains('e') || s.contains('E') {
        s
    } else {
        format!("{s}.0")
    }
}

fn binop_str(op: eidos_parser::BinOp) -> &'static str {
    use eidos_parser::BinOp;
    match op {
        BinOp::Add => "+",
        BinOp::Sub => "-",
        BinOp::Mul => "*",
        BinOp::Div => "/",
        BinOp::Rem => "%",
        BinOp::Lt => "<",
        BinOp::Gt => ">",
        BinOp::Le => "<=",
        BinOp::Ge => ">=",
        BinOp::Eq => "==",
        BinOp::Ne => "!=",
        BinOp::And => "&&",
        BinOp::Or => "||",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use eidos_erasure::erase;
    use eidos_parser::parse;

    fn gen_src(src: &str) -> String {
        let m = parse(src).expect("parse");
        let core = erase(&m);
        codegen(&core)
    }

    #[test]
    fn emits_no_std_and_helpers() {
        let out = gen_src("fn f(a: f64) -> f64 { return a + 1.0; }");
        assert!(out.contains("#![no_std]"));
        assert!(out.contains("pub fn eidos_map"));
        assert!(out.contains("pub fn eidos_magnitude"));
    }

    #[test]
    fn emits_struct_for_refinement() {
        let out = gen_src(
            "type NV = { v: Array<f64, 1> | v.magnitude() <= 1.0 };
             fn f(x: f64) -> NV { return { v: [x] } as NV; }",
        );
        assert!(out.contains("pub struct NV"));
        assert!(out.contains("pub v: [f64; 1],"));
        assert!(out.contains("NV { v: [x] }"), "got:\n{out}");
    }

    #[test]
    fn emits_map_zip_pipeline() {
        let out = gen_src(
            "fn f(a: Array<f64, 3>, b: Array<f64, 3>) -> Array<f64, 3> {
                return a.zip(b).map(|(x, y)| x - y);
            }",
        );
        assert!(
            out.contains("eidos_map(eidos_zip(a, b), |(x, y)|"),
            "got:\n{out}"
        );
    }

    #[test]
    fn no_kernel_types_leak() {
        let out = gen_src(
            "type NV = { v: Array<f64, 3> | v.magnitude() <= 1.0 };
             fn g(a: Array<f64, 3>) -> NV requires a.magnitude() > 0.0 {
                 if a.magnitude() > 0.0 { return { v: a.map(|x| x) } as NV; }
                 else { return { v: [0.0, 0.0, 0.0] } as NV; }
             }",
        );
        assert!(!out.contains("Refine"));
        assert!(!out.contains("Constraint"));
        assert!(!out.contains("eidos_kernel"));
        assert!(!out.contains("eidos_verifier"));
    }
}
